### PR TITLE
fix bugs in schedule editor component

### LINKED ISSUE #1169: UI update: add icon for "Prioritize" button
I don't have an icon for the "Prioritize" button on a schedule:

Image

It should have one.

### LINKED ISSUE #1170: UI update: debounce modifications to image name
https://github.com/user-attachments/assets/86b35bdf-2fd1-4113-a278-a5cc68aa1eef

We should wait for user to have completed what he is writing before firing query to get image tags. Probably wait something like 1s without input. Image tags should also be updated when user is leaving the textbox (and value has changed).

### LINKED ISSUE #1172: UI update: impossible to disable a recipe
https://github.com/user-attachments/assets/8b2ec18e-d4ca-49b2-b669-7e4482488211

### PR DESCRIPTION
**Pull request by elfkuzco**
## Changes
- update schedule field if it is not None (unset) on backend. This closes #1172
- use debounce mechanism to fetch image tags when changing image name. This closes #1170 
- add icon for prioritize icon.. This closes #1169

### CODE REVIEW

File: frontend-ui/src/components/ScheduleActionButton.vue [hunk 1]
```diff
@@ -122,7 +122,7 @@
       :disabled="working"
       @click="emit('fire-existing-task')"
     >
-      <v-icon size="small" class="mr-1">mdi-sort-amount-up</v-icon>
+      <v-icon size="small" class="mr-1">mdi-fire</v-icon>
```
Comment (benoit74) [inline frontend-ui/src/components/ScheduleActionButton.vue:125]: I'm sorry, I just realize we have the same issue with the "Request with high priority" button:

image
